### ISSUE TITLE
pipenv run python -m bumper Error

### ISSUE THREAD

**Issue by AndreiKorchunov** [bmartin5692/bumper#140]
**Describe the bug**
When I run in command window "pipenv run python -m bumper" then I get the error:

c:\Ecovacs>pipenv run python -m bumper
Traceback (most recent call last):
  File "<frozen runpy>", line 189, in _run_module_as_main
  File "<frozen runpy>", line 148, in _get_module_details
  File "<frozen runpy>", line 112, in _get_module_details
  File "c:\Ecovacs\bumper\__init__.py", line 3, in <module>
    from bumper.confserver import ConfServer
  File "c:\Ecovacs\bumper\confserver.py", line 8, in <module>
    import aiohttp_jinja2
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp_jinja2\__init__.py", line 7, in <module>
    from aiohttp import web
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import BaseConnector as BaseConnector
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp\client.py", line 32, in <module>
    from . import hdrs, http, payload
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp\http.py", line 7, in <module>
    from .http_parser import HeadersParser as HeadersParser
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp\http_parser.py", line 15, in <module>
    from .helpers import NO_EXTENSIONS, BaseTimerContext
  File "C:\Users\Андрей\.virtualenvs\Ecovacs-uviCpvCh\Lib\site-packages\aiohttp\helpers.py", line 100, in <module>
    old_debug = coroutines._DEBUG  # type: ignore
                ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio.coroutines' has no attribute '_DEBUG'

**To Reproduce**
1 download project to c:\Ecovacs
2 cd to c:\Ecovacs
3 run "pipenv install"
4 run "pipenv run python -m bumper"
5. See error

**Desktop (please complete the following information):**
 - OS: Windows

**Vacuum (please complete the following information):**
 - Model: Deebot Ozmo T8+

**Comment by blanky0230** [comment]
I suppose you are using python 3.11?
This project does not run with python 3.11. I think the latest supported version was 3.7.

Maybe have a look at https://github.com/pyenv/pyenv 

But keep in mind that python3.7 has reached EOL and may not receive security updates.

**Comment by moses19850** [comment]
Hi, have a similar issue
`root@bumper:~/bumper# pipenv run python -m bumper
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/root/bumper/bumper/__init__.py", line 3, in <module>
    from bumper.confserver import ConfServer
  File "/root/bumper/bumper/confserver.py", line 8, in <module>
    import aiohttp_jinja2
ModuleNotFoundError: No module named 'aiohttp_jinja2'`

Can someone please advice what is wrong? I installed aiotttp twice, one time directly in the bumper folder and one time outside. Nothing works.
Thanks
