### ISSUE TITLE
invalid HTTP method

### ISSUE THREAD

**Issue by protoszerg** [bmartin5692/bumper#141]
ERROR :: aiohttp.server :: Error handling request Traceback (most recent call last):
File "C:\Users\NguyenTienNam\.virtualenvs\Scripts-d0-A6Gqz\lib\site-packages\aiohttp\web_protocol.py", line 275, in data_received
messages, upgraded, tail = self._request_parser.feed_data(data)
File "aiohttp\_http_parser.pyx", line 523, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: invalid HTTP method

How can i fix this?

**Comment by LittleRandom** [comment]
That's likely an installation problem with your python. It seems like if you build straight from the Dockerfile, this issue gets fixed. I'm thinking it's likely due to some inconsistencies with dependencies.
